### ISSUE TITLE
setup entity source proxies

### ISSUE THREAD

**Issue by jchartrand** [cwrc/CWRC-GitWriter#10]
Setup nginx proxies on GitWriter server for entity sources that don't support https.

**Comment by jefferya** [comment]
@ilovan @SusanBrown  I don't understand the assignment to me as this references the GitWriter server? Or is the contents of this issue misleading and related to the e-mail from James?

**Comment by SusanBrown** [comment]
I believe this flows directly from the email exchange. The proxies for the entity sources need to be set up on the CWRC servers. James thought this would be very simple and quick to do but if you need further specifications from him pls ask.

On Jan 24, 2018, at 4:19 PM, Jeffery Antoniuk <notifications@github.com<mailto:notifications@github.com>> wrote:


@ilovan<https://github.com/ilovan> @SusanBrown<https://github.com/susanbrown> I don't understand the assignment to me as this references the GitWriter server? Or is the contents of this issue misleading and related to the e-mail from James?

**Comment by jchartrand** [comment]
Jeff has already done it.

**Comment by ilovan** [comment]
All existing entity lookups seem to be working now in GitWriter.
