### ISSUE TITLE
Document how we handle Github oauth

### ISSUE THREAD

**Issue by jchartrand** [cwrc/CWRC-GitWriter#11]

**Comment by jchartrand** [comment]
@ilovan  Where should I put this documentation?

**Comment by jchartrand** [comment]
Yes, it’s knowing which is the appropriate repo.  The authentication stuff kind of crosses repos/packages, so it might be better off in general documentation somewhere.  I think we have a documentation repo for the project as a whole?

**Comment by ilovan** [comment]
@jchartrand , would you agree that CWRC-GitWriter is the "main" GitHub repo for the Git-Writer code? If so, then please put it there. We currently don't have a technical documentation repo dedicated to CWRC_Writer in general or Git-Writer in particular (we have a tech documentation repo for CWRC in general, but I don't think this info is a good candidate for that repo, which contains servers and mirrors information, some API details, CWRC general development workflow, etc.).

**Comment by jchartrand** [comment]
Yes, sounds good.

**Comment by ilovan** [comment]
confirmed

**Comment by ilovan** [comment]
@ajmacdonald , can you please review existing documentation and adjust if/as needed?

**Comment by ilovan** [comment]
is this done, @ajmacdonald ?

**Comment by ajmacdonald** [comment]
@ilovan I've added an overview [here](https://github.com/cwrc/CWRC-GitWriter#authentication), with links to the GitHub technical documentation for a more detailed explanation

**Comment by ilovan** [comment]
thanks @ajmacdonald , will close for now
