### ISSUE TITLE
Relations tab is missing

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-GitWriter#18]
![image](https://user-images.githubusercontent.com/545952/36352654-36bf7fac-148a-11e8-84ef-0033d3a5ba02.png)

No form yet 
Browser: Chrome from MacBook Air
I'm guessing this is not browser specific. If it is, will try to replicate and provide more info.

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-DevGitWriter/commit/7ae6895f1bab13b0b718651d8fbdfc9116dd9d80
