### ISSUE TITLE
Blank document: revise

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-GitWriter#2]
1. Blank document open - default format TEI 
Step result: "Replace with your text" in the text area and some basic TEI structure in the structure panel
![screen shot 2017-11-07 at 11 10 51 am](https://user-images.githubusercontent.com/6600070/32510123-bcc170c6-c3ac-11e7-9279-6cb6510d557c.png)

2.User clicks on  "Edit source" 
Step result: Stump TEI document available in the edit panel
![screen shot 2017-11-07 at 11 15 19 am](https://user-images.githubusercontent.com/6600070/32510207-f85727b6-c3ac-11e7-9046-6ebafefc2d8b.png)

3. User changes the schema reference (Settings > Schema = "CWRC Entry Schema")
Step result: Text in the text area changes while structure in the structure panel remains TEI
![screen shot 2017-11-07 at 11 18 17 am](https://user-images.githubusercontent.com/6600070/32510310-63f1a2a8-c3ad-11e7-864f-b83bf5aaff25.png)

4. User clicks on "Edit source" again (e.g. to paste a chunk of XML)
Step result : "Edit source view" is empty (i.e. no structure, no text nodes)
![screen shot 2017-11-07 at 11 22 24 am](https://user-images.githubusercontent.com/6600070/32510476-f401e8d0-c3ad-11e7-9038-01d2c8d240ac.png)

**Comment by SusanBrown** [comment]
I think this might be ok at this point. @ilovan can you pls retest?

**Comment by ajmacdonald** [comment]
@ilovan @SusanBrown I can confirm this is still happening. Part of the problem is that the new schema is looking for a root element that doesn't exist in the document. What's the expected behaviour when you change to a different schema?

**Comment by SusanBrown** [comment]
Decision: given that the editor aims to support inexperienced users, the option to start with a blank document should be removed altogether.

**Comment by ajmacdonald** [comment]
Add warning when changing to a schema with a different root element.

**Comment by ajmacdonald** [comment]
I've re-opened this because no work has been done towards it.

**Comment by ajmacdonald** [comment]
@SusanBrown So do we really want to remove the "blank document" template?
It should be noted that the blank document is actually a very minimal TEI document.

**Comment by SusanBrown** [comment]
Thanks for checking. Can you link me to it so I can take a look? It’s not there in either the dev or prod cwrc-writer.

**Comment by ajmacdonald** [comment]
This is what it looks like
```
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://cwrc.ca/schemas/cwrc_tei_lite.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-stylesheet type="text/css" href="https://cwrc.ca/templates/css/tei.css"?>
<TEI xmlns="http://www.tei-c.org/ns/1.0" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
	xmlns:cw="http://cwrc.ca/ns/cw#" xmlns:w="http://cwrctc.artsrn.ualberta.ca/#">
	<teiHeader>
		<fileDesc>
			<titleStmt>
				<title>Sample Document Title</title>
			</titleStmt>
			<publicationStmt>
				<p></p>
			</publicationStmt>
			<sourceDesc sameAs="http://www.cwrc.ca">
				<p>Created from original research by members of CWRC/CSÉC unless
					otherwise noted.</p>
			</sourceDesc>
		</fileDesc>
	</teiHeader>
	<text>
		<body>
			<div> Replace with your text. </div>
		</body>
	</text>
</TEI>
```

**Comment by SusanBrown** [comment]
I think we should keep the blank document template. 

However, it is not valid if you replace the text. I believe that a P tag needs to be inserted inside the div to make it valid. I think too that it might be worth inserting a sample heading tag before this with "Replace with your title" inside it as well.

**Comment by ajmacdonald** [comment]
@SusanBrown @ilovan 
Changing the XML for the blank document led me to thinking about the teiHeader tag.
If we include it, the only way to modify it currently is by directly editing the XML, something which we're only recommending for "advanced users". If we don't include it, the user can't easily add it in.
Is this approach to the header tag still fine?

**Comment by SusanBrown** [comment]
Mihaela please put this on the agenda for discussion at our next meeting, but I think we are planning on sticking with this because the header is so flexible that when we’ve talked in the past about e.g. using a form (outside of CWRC) for it, it’s seemed like it would be too complicated to try to cover all the possibilities, and the fact that it is hidden make it difficult to edit in CWRC-Writer. So unless we have some new ideas, I think we should perhaps leave it as it is.



On Mar 5, 2018, at 1:47 PM, Andrew <notifications@github.com<mailto:notifications@github.com>> wrote:


@SusanBrown<https://github.com/susanbrown> @ilovan<https://github.com/ilovan>
Changing the XML for the blank document led me to thinking about the teiHeader tag.
If we include it, the only way to modify it currently is by directly editing the XML, something which we're only recommending for "advanced users". If we don't include it, the user can't easily add it in.
Is this approach to the header tag still fine?

**Comment by SusanBrown** [comment]
Decision: keep blank doc template. Starting new issue for header.

**Comment by ajmacdonald** [comment]
I'm re-opening because the contents of the blank document still need changing.

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/cwrc-git-dialogs/commit/b83389e495a30f8cdd7a080ef89d6ea62bcfa83d
