### ISSUE TITLE
Dockerize CWRC-Writer

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-GitWriter#26]
Will do collaboratively with TAMU.

Dockerize the GitWriter, not the Islandora CWRC-Writer.

Validation service -- dockerize this or keep it but then the dockerized version would depend on it
Proxies would also have to be dockerized and that means there will need to be a node.jx express server.
Lookups will remain web dependencies?

**Comment by ilovan** [comment]
Dockerized version available @ https://gitlab.dh.tamu.edu/bptarpley/CWRC-GitDocker
Live TAMU implementation @ http://cwrc.dh.tamu.edu

**Comment by ilovan** [comment]
Next step : @ilovan to ask re what he did re validation service and lookup proxies.
