### ISSUE TITLE
Install Google Analytics

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-GitWriter#27]

**Comment by ilovan** [comment]
@jchartrand , I just sent you an email with the Tracking ID, the code that needs to be added and where it needs to go for both Prod and Dev version of the site.

**Comment by SusanBrown** [comment]
Also look at what the npm repo and github analytics will provide.

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-GitWriter/commit/dbbdf979e146e69d5756db3710ec824e9bdc602d
https://github.com/cwrc/CWRC-DevGitWriter/commit/37d926dd6c74918cfe3fb15931677fbc2317a4a8

**Comment by ilovan** [comment]
First user statistics for Prod CWRC-Writer (first week of analytics):
![image](https://user-images.githubusercontent.com/6600070/38594840-9189262e-3d05-11e8-9294-a35a8c13f631.png)

**Comment by SusanBrown** [comment]
nice: not many but a good geographical spread, including some folks we don’t know.



On Apr 10, 2018, at 11:25 PM, Mihaela Ilovan <notifications@github.com<mailto:notifications@github.com>> wrote:


First user statistics for Prod CWRC-Writer (first week of analytics):
[image]<https://user-images.githubusercontent.com/6600070/38594840-9189262e-3d05-11e8-9294-a35a8c13f631.png>
