### ISSUE TITLE
New version lacks splash page, hence no document can be loaded. 

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-GitWriter#3]
After the "Authenticate with GitHub" popup, the Git-Writer is loaded without the intermediate splash screen and no document. 

![screen shot 2017-11-12 at 11 47 09 pm](https://user-images.githubusercontent.com/6600070/32713127-0d4fa510-c805-11e7-9d3a-1411f07e00bf.png)

**Comment by ilovan** [comment]
Tested in both FIrefox and Chrome with cache cleared.


@jchartrand , if you can fix this as soon as possible, that would be great.There is no way to load a doc in the GitWriter to test it right now.

**Comment by jchartrand** [comment]
I know what the problem is (absolute paths that should be relative).  Should be fixed today.  I’ll email when fixed.

**Comment by jchartrand** [comment]
Fixed.
