### ISSUE TITLE
Add save and exit functionality for Git-Writer

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-GitWriter#31]

**Comment by ilovan** [comment]
@SusanBrown , 

We have three different save types to support:

1. save document and remain in  the current session of GitWriter
2. save and exit  (within the same repo/file)
3. save as a new  repo/file (and exit?)

Any thought on how you would prefer this handled?
I would suggest a "simple save" button for 1 and a "save & manage" button for 2 and 3.

**Comment by SusanBrown** [comment]
I agree with the suggestion.

What I would like to overcome is the current effect produced by having the "leave" warning pop up when one clicks save. This is disconcerting given that one is not trying to leave the site and certainly not wanting to lose work, quite the reverse. So we want to disable that warning. 

![image](https://user-images.githubusercontent.com/545952/39241186-061e3b88-4854-11e8-8302-8430c4f9e63f.png)

**Comment by ajmacdonald** [comment]
@SusanBrown I'm having a look now at why the "leave" pop up appears when saving

**Comment by ajmacdonald** [comment]
"leave" pop-up fixed by https://github.com/cwrc/cwrc-git-dialogs/commit/7f8aa48e49ff4100cd895fc8bb6e8fb983d114a5

**Comment by SusanBrown** [comment]
:)

**Comment by SusanBrown** [comment]
That would be fine with me, I think.

**Comment by ilovan** [comment]
We currently have "save", "load" and "log out".
Let's see how this combination works for users.
