### ISSUE TITLE
Change error message when trying to save a new file to a repo you don't have access to.

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-GitWriter#36]
## Expected Behaviour

When the user hits "Save", run permissions check and if no write permission found: 
"You do not have writing permissions for the selected repository. Try saving as a pull request or save to another repository you have writing privileges for"

Return to save popup

## Current Behaviour

User is walked through all the steps (e.g. "check for repo existence, check for file existence, etc.) and gets the following message in the end:

![image](https://user-images.githubusercontent.com/6600070/48215175-e983b300-e33e-11e8-8ef3-3051f198f9c7.png)

## Steps to Reproduce 

1. Load any XML file, for example https://raw.githubusercontent.com/cwrc/CWRC-Schema/master/templates/place_entity_TEI_template.xml
2. Hit Save
3. Select a repo you don't have access to  (e.g. susanBrown/planet-susan
4. Add a file name
5. HIt Save

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/cwrc-git-dialogs/commit/8a52476bbc7e2f2151adbddf47daa564cc8b5e52
