### ISSUE TITLE
Unable to tag Title entities in Git-Writer

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-GitWriter#39]
## Expected Behaviour
being able to tag title entities using the ribbon

## Current Behaviour
being able to tag title entities using the ribbon doesn't work

## Steps to Reproduce 
Take normal steps to tag a title:
1. Select text
2. Click on "Tag title/text in the ribbon"
3. Select the item from the lookup
4. Clicked "Save" on the attributes dialog
Result: entity and tagging are not added to the document

## Your Environment
* URL: cwrc-writer.cwrc.ca (Firefox Mac)

**Comment by ajmacdonald** [comment]
@ilovan I'm having trouble reproducing this (and I'm using Firefox on a Mac)

**Comment by ilovan** [comment]
can't reproduce anymore either, will close for now
