### ISSUE TITLE
Add GitServer support for schemas hosted on GitHUb (https)

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-GitWriter#40]
Allow users to load documents that reference schemas hosted on GitHUb in their schema declaration.

**Comment by ajmacdonald** [comment]
This is supported already, as long as one uses the "raw" option when getting the link to the schema, e.g. https://raw.githubusercontent.com/ajmacdonald/gitwriter/master/epidoc.rng

**Comment by ilovan** [comment]
Still not working, apparently:

See https://dev-cwrc-writer.cwrc.ca/?githubPath=diane-mortimer_sarah-v2.xml&githubRepo=ilovan%2FGit-Writer_external_users_debugging

The schema declared is raw.githubusercontent.com/djakacki/moravianlives/master/TEI_Memoirs/out/MoravianMemoirs.rng

**Comment by ajmacdonald** [comment]
So the issue there is that there is no protocol/scheme is specified, e.g. http

**Comment by ilovan** [comment]
right  - thanks @ajmacdonald
