### ISSUE TITLE
Provide linkable urls for Git-Writer 

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-GitWriter#43]
One can't currently link directly to a Git-Writer-enabled document and get the GitWriter interface

@ajmacdonald would there be a way of creating a URL that got one to the GitWriter view of the raw GitHub file?

**Comment by ajmacdonald** [comment]
Yes that should be doable.

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/cwrc-git-dialogs/commit/5723f6ad557fc4ba945cf4118b75606b60f276ae

**Comment by ilovan** [comment]
confirmed on cwrc-writer.cwrc.ca
