### ISSUE TITLE
Git-Writer landing page: remove reference & link to the old sandbox

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-GitWriter#44]
## Expected Behaviour

Text should say: 

```You must first authenticate through Github to allow the CWRC-Writer to make calls on your behalf. CWRC does not keep any of your github information. The github token issued by github is not stored on a CWRC-Server, but is only submitted as a jwt token for each request you make. ```

## Current Behaviour

![Screen Shot 2019-02-04 at 12.15.33 PM.png](https://images.zenhubusercontent.com/5a5e621f4b5806bc2bc2ff7d/04f6ccef-1654-452d-a466-058a34adf5d9)

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/cwrc-git-dialogs/commit/782022ed87b5d1f55e6a8158546796c86df21ba1

**Comment by ilovan** [comment]
superseded by newer changes to the git dialogs
