### ISSUE TITLE
Git-Writer landing page: remove orphaned checkbox

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-GitWriter#45]
## Expected Behaviour

no orphaned checkbox at the top right corner of the landing page

## Current Behaviour

![Screen Shot 2019-02-04 at 12.15.33 PM.png](https://images.zenhubusercontent.com/5a5e621f4b5806bc2bc2ff7d/ad824fc7-5ea5-43f3-a3e8-e4a697851520)

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/cwrc-git-dialogs/commit/782022ed87b5d1f55e6a8158546796c86df21ba1

**Comment by ilovan** [comment]
confirmed
