### ISSUE TITLE
Git-Writer document saving dialog: caching of the first inputed repository an file name persists throughout the work session

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-GitWriter#46]
## Expected Behaviour

Ideally:
Git-Writer should remember what repo/doc pair it opened last and pre-populate the save dialog with those values (essentially making "SaveAs" as the default save option)

If this is not possible, then don't pre-populate the "save" dialog with any value. 

## Current Behaviour

1. user opens and edits a document in Git-Writer
2. User clicks on "Save" in the ribbon
3. User populates the "repository" and "file" fields in the "Save" popup and saves the file
4. User loads and edits another document
5. User clicks on "Save" in the ribbon
       Step result: the "Save popup opens pre-populated with the values selected at step no.3
6. User provides a different repo/file pair in the "save" dialog and saves the second document
7. User loads and edits a third document
8. User clicks on "Save" in the ribbon
       Step result: the "Save popup opens pre-populated with the values selected at step no.3
9.  User provides a different repo/file pair in the "save" dialog and saves the second document
Steps 7-9 repeated to the end of the work session.

**Comment by ajmacdonald** [comment]
I'm having trouble reproducing this. For me, the save fields are populated with repository and document name used to load the document.

**Comment by ilovan** [comment]
I am unable to reproduce this either., It's either been fixed or a one time weird occurrence
