### ISSUE TITLE
Unable to load documents that were saved with JSON-LD annotations.

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-GitWriter#48]
Examples:
https://github.com/ilovan/Side-by-side-test-no-pb-/blob/master/document.xml
and 
https://github.com/ilovan/RDFtestGitWriter/blob/master/testJan2019

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/d464025232df3b74d3191d37019ad1ce41b0be82

**Comment by ilovan** [comment]
@ajmacdonald , this is still an issue in dev-02 (see: https://dev-02.cwrc.ca/islandora/object/cwrc:8ba71b16-4435-442e-9418-89703f2d80de#)

though it does seem to be fixed in dev-cwrc-writer (see https://github.com/ilovan/Git-Writer-tests/blob/master/JSONtestSave.xml)

**Comment by ajmacdonald** [comment]
I've updated dev-02.
