### ISSUE TITLE
New GitHub users are unable to authenticate with GitHub

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-GitWriter#50]
After they log in to GitHub, when they return to the Git-Writer popup and click on "Authenticate with GitHub", nothing happens.

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/cwrc-git-dialogs/commit/9e056cd5e3e684daf21fff374774ef8fa78b9c5c

**Comment by ilovan** [comment]
confirmed
