### ISSUE TITLE
Save dialog does not recognize an existing file as such

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-GitWriter#54]
Repo:

https://dev-cwrc-writer.cwrc.ca/?githubPath=document.xml&githubRepo=ilovan%2FTo-Autumn-by-John-Keats

Behaviour:
![Jul-08-2019 10-19-44](https://user-images.githubusercontent.com/6600070/60825905-f83e9600-a169-11e9-9ecc-54b40a78ad0e.gif)

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/cwrc-git-dialogs/commit/2c34041b309cacd22f555fc8d04835ae82c8a09b

**Comment by ilovan** [comment]
confirmed on cwrc-writer.cwrc.ca
