### ISSUE TITLE
Change label in the Document save popup from "GitHub User" to "GitHub User/Organization"

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-GitWriter#62]
![image.png](https://images.zenhubusercontent.com/5a5e621f4b5806bc2bc2ff7d/aba458f0-ef27-4261-b2a2-7693154a573d)

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/cwrc-git-dialogs/commit/ca19dedb619a047e952e1be00d2903cc91903974

**Comment by ilovan** [comment]
Confirmed on dev-cwrc-writer
