### ISSUE TITLE
Support for CWRC and Orlando schemas seems to be broken in GitWriter

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-GitWriter#64]
## Expected Behaviour
display text styled in the text area if URL of the stylesheet is https and CORS enabled (which the CWRC stylesheets should be)

## Current Behaviour
CWRC-WRITER unable to read CSS for CWRC documents uploaded from desktop (have not tested uploaded from an existing repo yet)

## Steps to Reproduce (for bugs)

1. Go to dev-cwrc-writer.cwrc.ca or cwrc-writer.cwrc.ca. Select "Upload file or text" in the load document popup
2. Upload a CWRC document (see examples at the URLs listed below)
Step result:
![image.png](https://images.zenhubusercontent.com/5a5e621f4b5806bc2bc2ff7d/bb766705-8675-4936-88ce-10948983c6a8)

## Some debugging:

Browser tools message:
![image.png](https://images.zenhubusercontent.com/5a5e621f4b5806bc2bc2ff7d/c960cba3-463d-4d9f-a1a5-8289bae2ec41)

even though 

![image.png](https://images.zenhubusercontent.com/5a5e621f4b5806bc2bc2ff7d/31513e90-852c-4874-90bc-02bcccdc366b)

## Your Environment
* URL: dev-cwrc-writer.cwrc.ca (upload doc from desktop);
* Uploaded example: https://dev-cwrc-writer.cwrc.ca/?githubPath=CWRCschema-document&githubRepo=ilovan%2FGit-Writer-tests

* Browser Name: Chrome Version 77.0.3865.90 (Official Build) (64-bit)

* Operating System: Mac OS 10.14.6 

* Attachements: 
    * documents to upload - any at https://drive.google.com/drive/folders/1Sr0MK_lz_ex4RKeeqDNWVWYQcOcIkNWV
   * document as uploaded at https://dev-cwrc-writer.cwrc.ca/?githubPath=CWRCschema-document&githubRepo=ilovan%2FGit-Writer-tests: https://drive.google.com/open?id=1GiVXUAc3Pn6viXn82hCPuhRqqJX7p0YO

**Comment by ajmacdonald** [comment]
This isn't an issue with the schemas so much as it is an issue with the HTTP 302 redirect that's being sent by the server when trying to access the CSS located at http://cwrc.ca/templates/css/css_managed_within_cwrc/ceww.css . For some reason the redirect location isn't being followed and I'm not yet sure why.

**Comment by ilovan** [comment]
why would you want to access http://cwrc.ca/templates/css/css_managed_within_cwrc/ceww.css when the stylesheet is now actually at https://cwrc.ca/templates/css/css_managed_within_cwrc/ceww.css (no redirect involved)

**Comment by ajmacdonald** [comment]
I was testing with documents from your driver folder, which point to the http css location. I don't encounter any issues when testing a document that points to the https css location.

**Comment by ilovan** [comment]
right - however, it seems to me that we have a separate problem:
in https://dev-cwrc-writer.cwrc.ca/?githubPath=CWRCschema-document&githubRepo=ilovan%2FGit-Writer-tests I must have manually changed it in "edit source", and it still doesn't work after that (it doesn't style the text area, though the warning message is no longer popping in)

**Comment by ajmacdonald** [comment]
That document is showing the tei css as the linked stylesheet.

**Comment by ilovan** [comment]
right, it is the tei stylesheet (I have a feeling it defaulted to that when it could not read the one that was listed in the file)

**Comment by ajmacdonald** [comment]
It looks like it did. It should default to the css associated with the schema, if there's none associated with the document (or in this case if it couldn't load the css associated with the document).
I'm not sure why it used the tei css if the cwrc schema was loaded.

If you can reproduce the problem and give me the steps I'll have a look.

**Comment by ilovan** [comment]
I can't seem to reproduce the switching to TEI css part - not sure what happened there. However, the css declared in the doc is still not read in any of the other docs in the folder I shared with you.

**Comment by ilovan** [comment]
closing this one as there are more specific issues in the hopper already
