### ISSUE TITLE
Detect calls to the http version of the cwrcwriter and advise the user that they should instead use https if possible

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-GitWriter#8]
Description# 

This solution would apply to both users who accidentally stumble upon the http version (e.g. they are using an older saved bookmark) and users who switch to the https version on purpose (see #7 ).

Warning popup:

> Accessing the http version of the Git-Writer may expose your GitHub account to security breaches. Please switch to the https version for increased security. 

Ideally: warning message contains two buttons at the button: One that says "Remain on http" and one that says "Switch to https"

@SusanBrown , please review and revise text as needed.

**Comment by SusanBrown** [comment]
No http version will be available.

**Comment by SusanBrown** [comment]
Is this still relevant or did we disallow (as I think) http altogether?



On Jan 10, 2018, at 3:35 PM, Mihaela Ilovan <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #8<https://github.com/cwrc/CWRC-GitWriter/issues/8> to @SusanBrown<https://github.com/susanbrown>.

**Comment by ilovan** [comment]
No longer relevant (all http attempts automatically redirect to https) - closed 2 months ago.
